# ---
set -sg escape-time 0

set -g base-index 1
set -g default-terminal "${TERM}"
set -g detach-on-destroy off
set -g focus-events on
set -g mouse on
set -g renumber-windows on
set -g set-titles on
set -g status-right "#{pane_id}"
set -as terminal-features ",${TERM}:RGB" 

setw -g aggressive-resize on
setw -g automatic-rename on
setw -g pane-base-index 1

# ---
bind r source-file ~/.config/tmux/tmux.conf\; display-message 'source-file $HOME/.config/tmux/tmux.conf'

unbind '"'
bind '"' split-window -v -c "#{pane_current_path}"

unbind %
bind % split-window -h -c "#{pane_current_path}"

unbind c
bind c new-window -c "#{pane_current_path}"

unbind f
bind f command-prompt -p "(find-window)" "find-window -N '%%'"
